# Generated by Django 2.1.4 on 2018-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20181219_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('guides_in_section', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='section',
            field=models.CharField(default='Other', max_length=50),
            preserve_default=False,
        ),
    ]
