# Generated by Django 2.1.4 on 2018-12-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20181225_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guides.Section'),
        ),
    ]
