# Generated by Django 2.1.4 on 2018-12-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20181225_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guide',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Section'),
        ),
    ]
