# Generated by Django 2.1.4 on 2019-01-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_guide_user_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='date_creation',
        ),
    ]
