# Generated by Django 2.1.4 on 2019-01-09 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0011_remove_guide_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='user_voted',
            field=models.ManyToManyField(blank=True, related_name='guide_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
