# Generated by Django 2.1.4 on 2019-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_auto_20190109_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='votes',
        ),
    ]
