# Generated by Django 2.1.5 on 2019-01-20 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_remove_guide_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
