# Generated by Django 2.1.5 on 2019-01-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0014_auto_20190120_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='guides_in_section',
        ),
    ]
