# Generated by Django 2.1.5 on 2019-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0015_remove_section_guides_in_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='tags',
        ),
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='guide_tags', to='guides.Tag'),
        ),
    ]
