# Generated by Django 2.1.5 on 2019-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0016_auto_20190128_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='preview',
            field=models.ImageField(upload_to='previews/'),
        ),
    ]
