# Generated by Django 2.1.5 on 2019-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0018_auto_20190204_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='preview',
            field=models.CharField(max_length=255),
        ),
    ]
