# Generated by Django 2.1.5 on 2019-02-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0020_auto_20190210_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='guide',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='guides.Guide'),
            preserve_default=False,
        ),
    ]
